[package]
name = "exprimo"
version = "0.1.6"
edition = "2021"
license = "MIT"
authors = ["joshua.tracey08@gmail.com"]
description = "Exprimo is a JavaScript expression evaluator written in Rust."
repository = "https://github.com/josh-tracey/exprimo"
readme = "README.md"
keywords = ["expression", "eval", "js-expression", "js-eval", "javascript"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rslint_parser = "~0.3"
scribe-rust = { version ="~0.1", optional = true }
serde = "~1"
serde_json = "~1"

[features]
default = []
logging = ["scribe-rust"]
