# https://circleci.com/docs/reusing-config#using-the-parameters-declaration
commands: # a reusable commands with parameters
  exec:
    parameters:
      cmd:
        type: string
      dir:
        default: "."
        type: string
    steps:
      - run:
          command: |
            cd <<parameters.dir>>
            <<parameters.cmd>>

jobs:

  exprimo-audit:
    executor:
      name: rust/default
      tag: "1.70"

    steps:
      - checkout
      - run:
          command: cargo install cargo-audit
      - run:
          command: cargo audit

  exprimo-check:
    executor:
      name: rust/default
      tag: "1.70"

    steps:
      - checkout
      - exec:
          cmd: |
            cargo check

  exprimo-tests:
    executor:
      name: rust/default
      tag: "1.70"

    steps:
      - checkout
      - run:
          command: cargo test

orbs:
  rust: circleci/rust@1.6.0

version: 2.1

workflows:

  exprimo:
    jobs:

      - exprimo-audit:
          filters:
            branches:
              only: main

      - exprimo-tests
